study_dbt:
  target: dev
  outputs:
    dev:
      account: jt76835.us-east-2.aws
      database: AIRBNB
      user: dbt
      password: dbtPassword123
      role: transform
      schema: dev
      threads: 1
      type: snowflake      
      warehouse: COMPUTE_WH
  
