@startmindmap

title "Layers"
footer Disponível em: https://github.com/acnaweb/dbt

*[#F8F8FF]  Layers

**[#LightGray] Raw Data
***_ Source: Transacionais, APIs, CSVs

**[#LightGray] Stagging
***_ Source: Raw Data
***_ Remoção de duplicatas, formatação de dadas, conversões

**[#LightGray] Core Models
***_ Source: Stagging
***_ Transformações, agregações, cálculos, criação de tabelas ou dimensões

**[#LightGray] Marts
***_ Source: Core Models
***_ Modelagem dimensional pronta para consumo
***_ Dimensões e Fatos


@endmindmap
